# Generated by Django 4.0.3 on 2022-04-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messegerequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('header', models.CharField(max_length=200)),
                ('urg', models.BooleanField()),
            ],
        ),
    ]
