# Generated by Django 4.0.3 on 2022-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messegerequest',
            name='volid',
            field=models.IntegerField(default=-1),
        ),
    ]
