# Generated by Django 3.0.2 on 2022-04-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volnteer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
