# Generated by Django 3.0.2 on 2022-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volnteer',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
