# Generated by Django 4.0.4 on 2022-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0002_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='volnteer',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
