# Generated by Django 4.0.3 on 2022-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0002_volnteer_is_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volnteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='volnteer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
