# Generated by Django 3.2.13 on 2022-05-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_volinstances'),
        ('voulnteers', '0003_volnteer_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='volnteer',
            name='volinstance',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.volinstances'),
            preserve_default=False,
        ),
    ]
