# Generated by Django 3.0.2 on 2022-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0003_alter_volnteer_first_name_alter_volnteer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volnteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='volnteer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
