# Generated by Django 4.0.3 on 2022-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0003_alter_volnteer_first_name_alter_volnteer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='volnteer',
            name='school_id',
            field=models.IntegerField(default=-1),
        ),
    ]
