# Generated by Django 4.0.3 on 2022-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0004_auto_20220414_1659'),
        ('voulnteers', '0004_volnteer_school_id'),
    ]

    operations = [
    ]
