# Generated by Django 4.0.3 on 2022-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0005_merge_0004_auto_20220414_1659_0004_volnteer_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volnteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='volnteer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
