# Generated by Django 4.0.3 on 2022-04-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voulnteers', '0007_volnteer_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volnteer',
            old_name='publications',
            new_name='schools',
        ),
    ]
