# Generated by Django 4.0.3 on 2022-05-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cons', models.CharField(max_length=200)),
                ('timesent', models.DateTimeField()),
                ('text', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volnteer_id', models.IntegerField()),
                ('timesent', models.DateTimeField()),
                ('text', models.CharField(max_length=400)),
                ('header', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='messegerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('header', models.CharField(max_length=200)),
                ('urg', models.BooleanField()),
                ('volid', models.IntegerField(default=-1)),
                ('timesent', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
                ('coord_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='schoolrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('school_id', models.IntegerField()),
                ('volnteer_id', models.IntegerField()),
                ('volnteer_name', models.CharField(max_length=200)),
            ],
        ),
    ]
