# Generated by Django 4.0.3 on 2022-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='volnteer_id',
            new_name='reciever_id',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='sender_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
