# Generated by Django 4.0.3 on 2022-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('x_axis', models.FloatField()),
                ('y_axis', models.FloatField()),
                ('coord_id', models.FloatField()),
            ],
        ),
    ]
