# Generated by Django 4.0.3 on 2022-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_volnteer_id_feedbacks_reciever_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='urg',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
