# Generated by Django 4.0.4 on 2022-05-23 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_feedbacks_is_read_feedbacks_urg'),
    ]

    operations = [
        migrations.CreateModel(
            name='volinstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('school_id', models.IntegerField()),
                ('cor_id', models.IntegerField()),
                ('starttime', models.DateTimeField()),
                ('endttime', models.DateTimeField()),
                ('volnteers', models.ManyToManyField(related_name='volnteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
