# Generated by Django 4.0.3 on 2022-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_messegerequest_id_alter_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('school_id', models.IntegerField()),
                ('volnteer_id', models.IntegerField()),
            ],
        ),
    ]
