# Generated by Django 4.0.3 on 2022-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_schoolrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrequest',
            name='volnteer_name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
