# Generated by Django 4.0.4 on 2022-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='volinstances',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
