# Generated by Django 4.0.3 on 2022-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_messegerequest_timesent'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volnteer_id', models.IntegerField()),
                ('timesent', models.DateTimeField()),
                ('text', models.CharField(max_length=400)),
                ('header', models.CharField(max_length=200)),
            ],
        ),
    ]
