# Generated by Django 4.0.3 on 2022-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cons', models.CharField(max_length=200)),
                ('timesent', models.DateTimeField()),
                ('text', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
